-- Enhanced Migration: Schema + Triggers
-- Generated: 2025-10-14T14:20:49.610Z
-- ============================================================================

-- ============================================================================
-- SCHEMA MIGRATION (Generated by Drizzle)
-- ============================================================================

CREATE INDEX "series_language_local_title_idx" ON "series" USING btree ("language_id","local_title");--> statement-breakpoint
ALTER TABLE "articles" ADD CONSTRAINT "articles_series_episode_unique" UNIQUE("series_id","episode_number");