// src/db/scripts/generate-migrations.ts

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';

type MigrationConfig = {
  migrationsDir: string;
  triggersFile: string;
  schemaFile: string;
  outputDir: string;
};

const config: MigrationConfig = {
  migrationsDir: './src/db/migrations',
  triggersFile: './src/db/triggers/sync-triggers.sql',
  schemaFile: './src/db/schema.ts',
  outputDir: './src/db/migrations',
};

/**
 * Generate migration with integrated triggers
 */
async function generateMigration(): Promise<void> {
  console.log('🔄 Generating database migration with triggers...');

  try {
    // Step 1: Generate standard drizzle migration
    console.log('📋 Generating Drizzle schema migration...');
    execSync('npx drizzle-kit generate', { stdio: 'inherit' });

    // Step 2: Get the latest migration file
    const latestMigrationFile = getLatestMigrationFile();
    if (!latestMigrationFile) {
      throw new Error('No migration file found after generation');
    }

    console.log(`📝 Found migration file: ${latestMigrationFile}`);

    // Step 3: Read the generated migration SQL
    const migrationPath = join(config.outputDir, latestMigrationFile);
    const migrationContent = readFileSync(migrationPath, 'utf8');

    // Step 4: Read the triggers SQL
    let triggersContent = '';
    if (existsSync(config.triggersFile)) {
      console.log('🎯 Reading trigger definitions...');
      triggersContent = readFileSync(config.triggersFile, 'utf8');
    }

    // Step 5: Combine migration and triggers
    const enhancedMigration = combineMigrationAndTriggers(migrationContent, triggersContent);

    // Step 6: Write the enhanced migration
    writeFileSync(migrationPath, enhancedMigration);

    console.log('✅ Enhanced migration generated successfully!');
    console.log(`📁 File: ${migrationPath}`);
    console.log('🚀 Run `npm run db:migrate` to apply the migration');

  } catch (error) {
    console.error('❌ Migration generation failed:', error);
    process.exit(1);
  }
}

/**
 * Get the latest migration file name
 */
function getLatestMigrationFile(): string | null {
  try {
    if (!existsSync(config.outputDir)) {
      return null;
    }

    const files = require('fs').readdirSync(config.outputDir);
    const sqlFiles = files
      .filter((file: string) => file.endsWith('.sql'))
      .sort()
      .reverse();

    return sqlFiles[0] || null;
  } catch (error) {
    console.error('Error reading migrations directory:', error);
    return null;
  }
}

/**
 * Combine migration SQL with triggers SQL
 */
function combineMigrationAndTriggers(migrationSql: string, triggersSql: string): string {
  const header = `-- Enhanced Migration: Schema + Triggers
-- Generated: ${new Date().toISOString()}
-- ============================================================================

`;

  const schemaSection = `-- ============================================================================
-- SCHEMA MIGRATION (Generated by Drizzle)
-- ============================================================================

${migrationSql}

`;

  const triggersSection = triggersSql ? `-- ============================================================================
-- DATABASE TRIGGERS (Automatic Synchronization)
-- ============================================================================

${triggersSql}

` : '';

  const footer = `-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- This migration includes:
-- 1. Schema changes (tables, columns, indexes, constraints)
-- 2. Database triggers for automatic data synchronization
-- 3. Multilingual translation table management
-- 4. Series statistics and episode number management
-- 5. Publication event tracking
-- ============================================================================
`;

  return header + schemaSection + triggersSection + footer;
}

/**
 * Validate migration before generation
 */
function validatePrerequisites(): void {
  console.log('🔍 Validating prerequisites...');

  // Check if schema file exists
  if (!existsSync(config.schemaFile)) {
    throw new Error(`Schema file not found: ${config.schemaFile}`);
  }

  // Check if drizzle-kit is available
  try {
    execSync('npx drizzle-kit --version', { stdio: 'ignore' });
  } catch (error) {
    throw new Error('drizzle-kit not found. Please install with: npm install drizzle-kit');
  }

  // Ensure migrations directory exists
  if (!existsSync(config.migrationsDir)) {
    console.log('📁 Creating migrations directory...');
    mkdirSync(config.migrationsDir, { recursive: true });
  }

  // Ensure triggers directory exists
  const triggersDir = join('./src/db/triggers');
  if (!existsSync(triggersDir)) {
    console.log('📁 Creating triggers directory...');
    mkdirSync(triggersDir, { recursive: true });
  }

  console.log('✅ Prerequisites validated');
}

/**
 * Show migration preview
 */
function showMigrationPreview(): void {
  console.log(`
🔧 Migration Configuration:
   Schema File: ${config.schemaFile}
   Triggers File: ${config.triggersFile}
   Output Directory: ${config.outputDir}

📋 This migration will include:
   ✅ Schema changes (tables, indexes, constraints)
   ✅ Translation tables for multilingual support
   ✅ Series management with episode tracking
   ✅ Denormalized fields for performance
   ✅ Database triggers for auto-synchronization
   ✅ Publication event tracking
   ✅ Enhanced audit trails

⚠️  Make sure to backup your database before running this migration!
`);
}

/**
 * Generate migration status report
 */
function generateStatusReport(migrationFile: string): void {
  const migrationPath = join(config.outputDir, migrationFile);
  const stats = require('fs').statSync(migrationPath);
  const content = readFileSync(migrationPath, 'utf8');

  // Count different sections
  const tableCount = (content.match(/CREATE TABLE/g) || []).length;
  const indexCount = (content.match(/CREATE INDEX/g) || []).length;
  const triggerCount = (content.match(/CREATE TRIGGER/g) || []).length;
  const functionCount = (content.match(/CREATE OR REPLACE FUNCTION/g) || []).length;

  console.log(`
📊 Migration Statistics:
   File Size: ${Math.round(stats.size / 1024)}KB
   Tables: ${tableCount}
   Indexes: ${indexCount}
   Functions: ${functionCount}
   Triggers: ${triggerCount}
   
🚀 Next Steps:
   1. Review the generated migration: ${migrationPath}
   2. Backup your database
   3. Run: npm run db:migrate
   4. Test the new features
`);
}

/**
 * Main execution
 */
async function main(): Promise<void> {
  try {
    console.log('🚀 Enhanced Database Migration Generator');
    console.log('==========================================\n');

    validatePrerequisites();
    showMigrationPreview();

    // Wait for user confirmation in interactive mode
    if (process.env.NODE_ENV !== 'ci') {
      console.log('Press Ctrl+C to cancel, or any key to continue...');
      await new Promise(resolve => {
        process.stdin.once('data', resolve);
        setTimeout(resolve, 5000); // Auto-continue after 5 seconds
      });
    }

    await generateMigration();

    const latestFile = getLatestMigrationFile();
    if (latestFile) {
      generateStatusReport(latestFile);
    }

  } catch (error) {
    console.error('❌ Migration generation failed:', error);
    process.exit(1);
  }
}

// Run the migration generator
if (require.main === module) {
  main();
}

export { generateMigration, validatePrerequisites };
